'use client'
import {useState} from 'react'
import Header from '@/components/Header'
const restrictions=['peanut','tree_nut','milk','egg','soy','wheat','sesame'] as const
const blank=()=>({id:crypto.randomUUID(),name:'',ingredients:'',allergenStatement:'',labelComplete:false,evidenceSource:'',price:undefined as number|undefined})
type Product=ReturnType<typeof blank>
type Result={runId:string;mode:string;sourceMode:string;plan:string[];products:Array<{id:string;name:string;status:string;reasons:string[];evidenceSource:string}>;shortlist:string[];steps:Array<{id:number;tool:string;status:string;description:string;durationMs:number}>;saved:boolean;retrievalError:string|null;safety:string;limitations:string[]}
export default function GuardianAgentPage(){
  const [goal,setGoal]=useState('Find suitable breakfast products for my dietary restrictions and budget.')
  const [constraints,setConstraints]=useState<string[]>(['peanut'])
  const [budget,setBudget]=useState('500')
  const [currency,setCurrency]=useState<'INR'|'AED'|'USD'>('INR')
  const [allowCatalogSearch,setSearch]=useState(false)
  const [approveSave,setSave]=useState(false)
  const [products,setProducts]=useState<Product[]>([blank()])
  const [result,setResult]=useState<Result|null>(null)
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const update=(id:string,patch:Partial<Product>)=>setProducts(current=>current.map(p=>p.id===id?{...p,...patch}:p))
  async function run(){
    setError('');setResult(null);setBusy(true)
    try{
      const validProducts=products.filter(p=>p.name.trim()||p.ingredients.trim()||p.allergenStatement.trim())
      if(validProducts.some(p=>!p.name.trim()||!p.evidenceSource.trim()))throw new Error('Each entered product needs a name and evidence reference. Leave all fields blank to search only via a connected catalogue.')
      const response=await fetch('/api/guardian/agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal,constraints,budget:budget?Number(budget):undefined,currency,allowCatalogSearch,products:validProducts.length?validProducts:undefined,maxResults:5,approvedActions:approveSave?['save_shortlist']:[]})})
      const data=await response.json();if(!response.ok)throw new Error(data.error||'Agent request failed')
      setResult(data)
    }catch(e){setError(e instanceof Error?e.message:'Unable to start agent')}finally{setBusy(false)}
  }
  return <div className="min-h-screen bg-zinc-950 text-zinc-100"><Header/><main className="mx-auto max-w-5xl space-y-7 px-4 py-10">
    <div><a href="/guardian" className="text-emerald-300 text-sm">← Original Guardian evidence checker</a><p className="text-xs uppercase tracking-widest text-emerald-400 mt-4">ScanSafe Guardian • Agent workspace</p><h1 className="text-3xl font-bold mt-2">Food research agent</h1><p className="text-zinc-400 mt-3">Runs a bounded, auditable research workflow. Connected catalogue retrieval requires your administrator to configure a trusted provider. It never fabricates products, prices or allergen declarations.</p></div>
    <section className="rounded-xl bg-zinc-900 border border-zinc-800 p-5 space-y-4"><h2 className="text-xl font-semibold">1. Give Guardian a goal</h2><textarea aria-label="Research goal" className="w-full rounded-lg p-3 bg-zinc-950 border border-zinc-700" rows={2} maxLength={500} value={goal} onChange={e=>setGoal(e.target.value)}/><div className="flex flex-wrap gap-2">{restrictions.map(c=><button type="button" key={c} onClick={()=>setConstraints(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c])} className={'border rounded-full px-3 py-2 text-sm '+(constraints.includes(c)?'bg-emerald-800 border-emerald-500':'border-zinc-700')}>{c.replace('_',' ')}</button>)}</div><div className="flex gap-3 flex-wrap"><label className="text-sm">Budget per product<input aria-label="Budget" className="block p-3 bg-zinc-950 border border-zinc-700 rounded-lg mt-1" type="number" min="1" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label className="text-sm">Currency<select className="block p-3 bg-zinc-950 border border-zinc-700 rounded-lg mt-1" value={currency} onChange={e=>setCurrency(e.target.value as typeof currency)}><option>INR</option><option>AED</option><option>USD</option></select></label></div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={allowCatalogSearch} onChange={e=>setSearch(e.target.checked)}/> Search connected, authorized product catalogue (if configured)</label><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={approveSave} onChange={e=>setSave(e.target.checked)}/> I approve saving this shortlist to my signed-in account</label></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">2. Provide evidence (optional if a catalogue is connected)</h2><p className="text-amber-200 text-sm">For a meaningful result, add accurate ingredient and allergen statements from the same package. A product with missing evidence cannot be certified safe.</p>{products.map((p,i)=><div key={p.id} className="rounded-xl bg-zinc-900 border border-zinc-800 p-4 space-y-3"><div className="flex justify-between"><strong>Product {i+1}</strong><button disabled={products.length===1} className="text-red-300 text-sm disabled:opacity-30" onClick={()=>setProducts(v=>v.filter(x=>x.id!==p.id))}>Remove</button></div><input aria-label="Product name" placeholder="Product name" className="w-full p-3 bg-zinc-950 border border-zinc-700 rounded-lg" value={p.name} onChange={e=>update(p.id,{name:e.target.value})}/><textarea aria-label="Ingredients" placeholder="Ingredients, exactly as printed" className="w-full p-3 bg-zinc-950 border border-zinc-700 rounded-lg" value={p.ingredients} onChange={e=>update(p.id,{ingredients:e.target.value})}/><textarea aria-label="Allergen declaration" placeholder="Allergen / may-contain declaration" className="w-full p-3 bg-zinc-950 border border-zinc-700 rounded-lg" value={p.allergenStatement} onChange={e=>update(p.id,{allergenStatement:e.target.value})}/><input aria-label="Evidence reference" placeholder="Manufacturer URL or package photo reference" className="w-full p-3 bg-zinc-950 border border-zinc-700 rounded-lg" value={p.evidenceSource} onChange={e=>update(p.id,{evidenceSource:e.target.value})}/><label className="text-sm">Price <input aria-label="Product price" type="number" min="0" className="p-2 bg-zinc-950 border border-zinc-700 rounded-lg ml-2" value={p.price??''} onChange={e=>update(p.id,{price:e.target.value?Number(e.target.value):undefined})}/></label><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={p.labelComplete} onChange={e=>update(p.id,{labelComplete:e.target.checked})}/> Both ingredient and allergen statements are complete and legible</label></div>)}<button type="button" disabled={products.length>=20} onClick={()=>setProducts(v=>[...v,blank()])} className="border border-zinc-700 rounded-lg px-4 py-2">+ Add another product</button></section>
    <button onClick={run} disabled={busy||!constraints.length} className="bg-emerald-500 text-zinc-950 rounded-lg px-6 py-3 font-bold disabled:opacity-40">{busy?'Executing tools…':'Run Guardian agent'}</button>{error&&<p role="alert" className="text-red-300">{error}</p>}
    {result&&<section aria-live="polite" className="space-y-4"><h2 className="text-2xl font-bold">3. Agent report</h2><p className="text-xs text-zinc-400">{result.runId} · {result.mode} · {result.sourceMode}</p>{result.retrievalError&&<p className="text-amber-200">Catalogue connection error: {result.retrievalError}</p>}<div className="grid gap-3">{result.products.map(p=><article key={p.id} className="border border-zinc-700 rounded-xl p-4"><div className="flex justify-between flex-wrap gap-2"><strong>{p.name}</strong><span className={p.status==='candidate'?'text-emerald-300':p.status==='excluded'?'text-red-300':'text-amber-300'}>{p.status.toUpperCase().replace('_',' ')}</span></div><p className="text-zinc-400 text-sm mt-2">{p.reasons.join(' ')}</p><p className="text-xs text-zinc-500 mt-1">Source (not independently certified): {p.evidenceSource}</p></article>)}</div><div className="bg-zinc-900 rounded-xl p-4"><h3 className="font-bold">Comparison shortlist — not a safety approval</h3>{result.shortlist.length?result.shortlist.map(id=><p key={id} className="mt-2">{result.products.find(p=>p.id===id)?.name??id}</p>):<p className="mt-2 text-zinc-400">No sufficiently documented comparison candidates. Supply evidence or configure a source.</p>}<p className="text-xs text-zinc-400 mt-3">Saved to account: {result.saved?'Yes':'No'}</p></div><details className="border border-zinc-700 p-4 rounded-xl"><summary className="font-semibold cursor-pointer">Tool execution and retry trace ({result.steps.length})</summary><ol className="mt-3 space-y-2 text-sm">{result.steps.map(s=><li key={s.id}><strong>{s.tool}</strong> · {s.status} ({s.durationMs}ms) — {s.description}</li>)}</ol></details><p className="text-amber-200 text-sm">{result.safety}</p>{result.limitations.map(x=><p key={x} className="text-xs text-zinc-400">• {x}</p>)}</section>}
  </main></div>
}
