'use client'

import { useState } from 'react'
import Header from '@/components/Header'
import type { GuardianRequest } from '@/lib/guardian'

type GuardianResult = {runId: string; mode: string; products: Array<{id: string; name: string; price: number | null; evidenceSource: string; status: string; reasons: string[]}>; shortlist: string[]; steps: Array<{tool: string; detail: string}>; limitations: string[]}
const blankProduct = () => ({ id: crypto.randomUUID(), name: '', ingredients: '', allergenStatement: '', labelComplete: false, evidenceSource: '', price: undefined as number | undefined })
const choices = ['peanut','tree_nut','milk','egg','soy','wheat','sesame'] as const
export default function GuardianPage() {
  const [goal, setGoal] = useState('Compare products for my dietary restrictions and budget.')
  const [constraints, setConstraints] = useState<string[]>(['peanut'])
  const [budget, setBudget] = useState('500')
  const [products, setProducts] = useState([blankProduct(), blankProduct()])
  const [result, setResult] = useState<GuardianResult | null>(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const update = (id: string, patch: Partial<(typeof products)[number]>) => setProducts(prev => prev.map(p => p.id === id ? {...p, ...patch} : p))
  async function run() {
    setError(''); setResult(null); setBusy(true)
    try {
      const payload: GuardianRequest = { goal, constraints: constraints as GuardianRequest['constraints'], currency: 'INR', ...(budget.trim() ? {budget: Number(budget)} : {}), products }
      const response = await fetch('/api/guardian', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(payload) })
      const data = await response.json()
      if (!response.ok) throw new Error(data.error || 'Unable to evaluate products. Complete all required fields.')
      setResult(data)
    } catch(e) { setError(e instanceof Error ? e.message : 'Request failed') } finally {setBusy(false)}
  }
  return <div className="min-h-screen bg-zinc-950 text-white"><Header/><main className="mx-auto max-w-5xl px-4 py-12 space-y-8">
    <div><a href="/guardian/agent" className="inline-flex rounded-lg bg-emerald-500 px-4 py-3 text-zinc-950 font-bold mb-5">Open Guardian Agent Workspace →</a><p className="text-emerald-400 text-sm font-bold tracking-widest uppercase">ScanSafe / Guardian AI • Evidence-first prototype</p><h1 className="text-4xl font-extrabold mt-3">Your food research workspace</h1><p className="text-zinc-400 mt-3 max-w-3xl">This first release evaluates product label information that you enter. It does not search shops, confirm manufacturer statements, purchase food or claim medical safety.</p></div>
    <section className="rounded-2xl bg-zinc-900 border border-zinc-800 p-6 space-y-5"><h2 className="text-xl font-bold">1. Set your goal</h2><label className="block text-sm">What do you need?<textarea value={goal} onChange={e=>setGoal(e.target.value)} maxLength={500} rows={2} className="mt-2 w-full rounded-lg bg-zinc-950 border border-zinc-700 p-3"/></label><div><p className="text-sm mb-3">Ingredients to avoid (select at least one)</p><div className="flex gap-2 flex-wrap">{choices.map(c=><button key={c} onClick={()=>setConstraints(old=>old.includes(c)?old.filter(v=>v!==c):[...old,c])} className={`px-3 py-2 rounded-lg border text-sm ${constraints.includes(c)?'bg-emerald-900 border-emerald-500 text-emerald-100':'bg-zinc-950 border-zinc-700 text-zinc-300'}`}>{c.replace('_',' ')}</button>)}</div></div><label className="block text-sm">Maximum price per product (INR, optional)<input value={budget} onChange={e=>setBudget(e.target.value)} type="number" min="0" className="mt-2 block rounded-lg bg-zinc-950 border border-zinc-700 p-3"/></label></section>
    <section className="space-y-4"><h2 className="text-xl font-bold">2. Add products and their exact label details</h2><p className="text-sm text-amber-200">Copy the actual ingredients and allergen statement. A missing declaration must stay blank. Mark the label complete only when all required details are clearly visible.</p>{products.map((p,i)=><div key={p.id} className="rounded-xl bg-zinc-900 border border-zinc-800 p-5 space-y-3"><div className="flex justify-between"><h3 className="font-bold">Product {i+1}</h3><button className="text-red-300 text-sm" disabled={products.length===1} onClick={()=>setProducts(old=>old.filter(x=>x.id!==p.id))}>Remove</button></div><div className="grid md:grid-cols-2 gap-3"><input aria-label="Product name" placeholder="Product name" value={p.name} onChange={e=>update(p.id,{name:e.target.value})} className="p-3 rounded-lg bg-zinc-950 border border-zinc-700"/><input aria-label="Price in INR" type="number" min="0" placeholder="Price (optional)" value={p.price??''} onChange={e=>update(p.id,{price:e.target.value?Number(e.target.value):undefined})} className="p-3 rounded-lg bg-zinc-950 border border-zinc-700"/></div><textarea aria-label="Exact ingredients" placeholder="Exact ingredients from package" rows={2} value={p.ingredients} onChange={e=>update(p.id,{ingredients:e.target.value})} className="w-full p-3 rounded-lg bg-zinc-950 border border-zinc-700"/><textarea aria-label="Exact allergen statement" placeholder="Exact allergen / may-contain declaration" rows={2} value={p.allergenStatement} onChange={e=>update(p.id,{allergenStatement:e.target.value})} className="w-full p-3 rounded-lg bg-zinc-950 border border-zinc-700"/><input aria-label="Source reference" placeholder="Source: package photo filename, batch or manufacturer URL" value={p.evidenceSource} onChange={e=>update(p.id,{evidenceSource:e.target.value})} className="w-full p-3 rounded-lg bg-zinc-950 border border-zinc-700"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={p.labelComplete} onChange={e=>update(p.id,{labelComplete:e.target.checked})}/> I have the complete legible ingredients and allergen statement</label></div>)}<button disabled={products.length>=20} onClick={()=>setProducts(p=>[...p,blankProduct()])} className="px-4 py-2 border border-zinc-700 rounded-lg">+ Add product</button></section>
    <button disabled={busy||constraints.length===0} onClick={run} className="bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 text-zinc-950 font-bold rounded-xl px-6 py-4">{busy?'Checking evidence…':'Run Guardian evaluation'}</button>{error&&<p role="alert" className="text-red-300">{error}</p>}
    {result&&<section aria-live="polite" className="space-y-5"><h2 className="text-2xl font-bold">3. Guardian findings</h2><p className="text-sm text-zinc-400">Run ID: {result.runId} · {result.mode}</p>{result.products.map(p=><div key={p.id} className="bg-zinc-900 border border-zinc-800 p-5 rounded-xl"><div className="flex flex-wrap gap-2 justify-between"><h3 className="font-bold">{p.name}</h3><span className={p.status==='excluded'?'text-red-300':p.status==='needs_review'?'text-amber-300':'text-emerald-300'}>{p.status.replace('_',' ').toUpperCase()}</span></div><p className="text-xs text-zinc-400 mt-1">Source provided: {p.evidenceSource}</p><p className="text-sm text-zinc-400 mt-2">{p.reasons.join(' ')}</p></div>)}<div className="border border-emerald-900 bg-emerald-950/30 rounded-xl p-5"><h3 className="font-bold mb-2">Candidate shortlist — not safety certification</h3>{result.shortlist.length?result.shortlist.map(id=><p key={id}>{result.products.find(p=>p.id===id)?.name}</p>):<p>No candidate has sufficient submitted evidence for the shortlist.</p>}</div><details className="bg-zinc-900 rounded-xl p-5"><summary className="cursor-pointer font-semibold">Inspect agent execution trace</summary><ol className="mt-3 space-y-3 text-sm">{result.steps.map((s,i)=><li key={i}><strong>{s.tool}</strong> — {s.detail}</li>)}</ol></details><div className="text-sm text-amber-200 space-y-1">{result.limitations.map(l=><p key={l}>• {l}</p>)}</div></section>}
  </main></div>
}
